version: 0.1
phases:
  install: 
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - cd frontend && npm install
  build:
    commands:
      - cd frontend && npm run build
  post_build:
    commands:
      - pwd
      - cd build && aws s3 sync . $S3_BUCKET 